export const AvatarSystemStr = [
  'class AvatarSystem {',
  '  constructor(scene, startPosition) {',
  '    this.scene = scene;',
  '    this.position = startPosition.clone();',
  '    this.rotationY = 0;',
  '    this.group = new THREE.Group();',
  '    this.group.position.copy(this.position);',
  '    this.scene.add(this.group);',
  '    this.walkTime = 0;',
  '    this.idleTime = 0;',
  '    this.limbs = {};',
  '    this.buildMesh();',
  '  }',
  '  buildMesh() {',
  '    const bodyMat = new THREE.MeshStandardMaterial({ color: 0x3366cc, roughness: 0.6, metalness: 0.1 });',
  '    const body = new THREE.Mesh(new THREE.BoxGeometry(2.5, 4.5, 1.5), bodyMat);',
  '    body.position.y = 5.25; body.castShadow = true;',
  '    this.group.add(body);',
  '    const headMat = new THREE.MeshStandardMaterial({ color: 0xffccaa, roughness: 0.5 });',
  '    const head = new THREE.Mesh(new THREE.BoxGeometry(2, 2.5, 2), headMat);',
  '    head.position.y = 8.75; head.castShadow = true;',
  '    this.group.add(head);',
  '    const armMat = new THREE.MeshStandardMaterial({ color: 0x3366cc });',
  '    const armGeo = new THREE.BoxGeometry(1, 3.5, 1);',
  '    this.limbs.leftArm = new THREE.Group();',
  '    this.limbs.leftArm.position.set(-1.8, 7.0, 0);',
  '    const lArm = new THREE.Mesh(armGeo, armMat);',
  '    lArm.position.y = -1.5; lArm.castShadow = true;',
  '    this.limbs.leftArm.add(lArm);',
  '    this.group.add(this.limbs.leftArm);',
  '    this.limbs.rightArm = new THREE.Group();',
  '    this.limbs.rightArm.position.set(1.8, 7.0, 0);',
  '    const rArm = new THREE.Mesh(armGeo, armMat);',
  '    rArm.position.y = -1.5; rArm.castShadow = true;',
  '    this.limbs.rightArm.add(rArm);',
  '    this.group.add(this.limbs.rightArm);',
  '    const legMat = new THREE.MeshStandardMaterial({ color: 0x111111 });',
  '    const legGeo = new THREE.BoxGeometry(1.2, 4.0, 1.2);',
  '    this.limbs.leftLeg = new THREE.Group();',
  '    this.limbs.leftLeg.position.set(-0.8, 3.0, 0);',
  '    const lLeg = new THREE.Mesh(legGeo, legMat);',
  '    lLeg.position.y = -2.0; lLeg.castShadow = true;',
  '    this.limbs.leftLeg.add(lLeg);',
  '    this.group.add(this.limbs.leftLeg);',
  '    this.limbs.rightLeg = new THREE.Group();',
  '    this.limbs.rightLeg.position.set(0.8, 3.0, 0);',
  '    const rLeg = new THREE.Mesh(legGeo, legMat);',
  '    rLeg.position.y = -2.0; rLeg.castShadow = true;',
  '    this.limbs.rightLeg.add(rLeg);',
  '    this.group.add(this.limbs.rightLeg);',
  '  }',
  '  update(deltaTime, newPosition, velocityVec) {',
  '    const speed = velocityVec ? Math.sqrt(velocityVec.x**2 + velocityVec.z**2) : 0;',
  '    const isMoving = speed > 0.5;',
  '    if (newPosition) this.position.copy(newPosition);',
  '    this.idleTime += deltaTime * 2;',
  '    this.group.position.set(this.position.x, Math.sin(this.idleTime) * 0.05, this.position.z);',
  '    if (isMoving) {',
  '      const targetRot = Math.atan2(velocityVec.x, velocityVec.z);',
  '      let diff = targetRot - this.group.rotation.y;',
  '      while (diff < -Math.PI) diff += Math.PI * 2;',
  '      while (diff > Math.PI)  diff -= Math.PI * 2;',
  '      this.group.rotation.y += diff * 15 * deltaTime;',
  '      this.walkTime += speed * 0.8 * deltaTime;',
  '      const swing = Math.sin(this.walkTime) * 0.8;',
  '      this.limbs.leftArm.rotation.x  = -swing;',
  '      this.limbs.rightArm.rotation.x =  swing;',
  '      this.limbs.leftLeg.rotation.x  =  swing;',
  '      this.limbs.rightLeg.rotation.x = -swing;',
  '    } else {',
  '      const l = 10 * deltaTime;',
  '      this.limbs.leftArm.rotation.x  += (0 - this.limbs.leftArm.rotation.x)  * l;',
  '      this.limbs.rightArm.rotation.x += (0 - this.limbs.rightArm.rotation.x) * l;',
  '      this.limbs.leftLeg.rotation.x  += (0 - this.limbs.leftLeg.rotation.x)  * l;',
  '      this.limbs.rightLeg.rotation.x += (0 - this.limbs.rightLeg.rotation.x) * l;',
  '    }',
  '  }',
  '}',
].join('\n');
