export const CameraControllerStr = [
  'class CameraController {',
  '  constructor(camera) {',
  '    this.camera = camera;',
  '    this.smoothFactor = 4.0;',
  '    this.followMode = false;',
  '    this.camTarget = new THREE.Vector3();',
  '    this.radius = 420;',
  '    this.theta = -Math.PI / 4;',
  '    this.phi = Math.PI / 3.8;',
  '    this.zoomDelta = 0;',
  '  }',
  '  toggleFollowMode() { this.followMode = !this.followMode; return this.followMode; }',
  '  update(deltaTime, avatarPosition, orbitDelta, zoomDelta) {',
  '    if (zoomDelta !== 0) {',
  '      this.radius = Math.max(80, Math.min(900, this.radius + zoomDelta));',
  '    }',
  '    if (orbitDelta.x !== 0 || orbitDelta.y !== 0) {',
  '      this.theta -= orbitDelta.x;',
  '      this.phi -= orbitDelta.y;',
  '      this.phi = Math.max(0.1, Math.min(Math.PI / 2 - 0.1, this.phi));',
  '    }',
  '    if (this.followMode && avatarPosition) {',
  '      this.camTarget.lerp(avatarPosition, this.smoothFactor * deltaTime);',
  '    }',
  '    const x = this.camTarget.x + this.radius * Math.sin(this.phi) * Math.cos(this.theta);',
  '    const y = this.radius * Math.cos(this.phi);',
  '    const z = this.camTarget.z + this.radius * Math.sin(this.phi) * Math.sin(this.theta);',
  '    this.camera.position.set(x, Math.max(20, y), z);',
  '    this.camera.lookAt(this.camTarget);',
  '  }',
  '  setCamTarget(x, z) { this.camTarget.set(x, 0, z); }',
  '}',
].join('\n');
