export const EngineCoreStr = [
  'class EngineCore {',
  '  constructor() {',
  '    this.CONFIG = { BLOCK_W: 60, BLOCK_D: 60, ROAD_W: 28, COLS: 4, ROWS: 4 };',
  '    this.CITY_W = this.CONFIG.COLS * (this.CONFIG.BLOCK_W + this.CONFIG.ROAD_W) + this.CONFIG.ROAD_W;',
  '    this.CITY_D = this.CONFIG.ROWS * (this.CONFIG.BLOCK_D + this.CONFIG.ROAD_W) + this.CONFIG.ROAD_W;',
  '    this.startPos = new THREE.Vector3(this.CITY_W / 2, 0, this.CITY_D / 2);',
  '    this.clock = new THREE.Clock();',
  '    this.raycaster = new THREE.Raycaster();',
  '    this.hoveredMesh = null;',
  '    this.selectedShop = null;',
  '  }',
  '  init() {',
  '    try {',
  '      this.renderer = new THREE.WebGLRenderer({ antialias: true });',
  '      this.renderer.setSize(window.innerWidth, window.innerHeight);',
  '      this.renderer.shadowMap.enabled = true;',
  '      this.renderer.shadowMap.type = THREE.PCFSoftShadowMap;',
  '      this.renderer.setClearColor(0x0a0a2a, 1);',
  '      document.getElementById("canvas-container").appendChild(this.renderer.domElement);',
  '      this.scene = new THREE.Scene();',
  '      this.scene.fog = new THREE.FogExp2(0x0a0a2a, 0.0008);',
  '      this.camera = new THREE.PerspectiveCamera(55, window.innerWidth / window.innerHeight, 1, 2000);',
  '      this.inputMgr   = new InputManager(this.renderer.domElement);',
  '      this.physics     = new PhysicsController(this.CONFIG);',
  '      this.camCtrl     = new CameraController(this.camera);',
  '      this.envMgr      = new EnvironmentManager(this.scene, this.CONFIG, document.getElementById("minimap-canvas"));',
  '      this.shopMgr     = new ShopManager(this.scene);',
  '      this.avatarSys   = new AvatarSystem(this.scene, this.startPos);',
  '      this.envMgr.buildEnvironment();',
  '      this.shopMgr.generateEnvironment(this.CONFIG, window.STORES_FROM_APP || [], this.physics);',
  '      this.camCtrl.setCamTarget(this.startPos.x, this.startPos.z);',
  '      this.bindUI();',
  '      window.addEventListener("resize", () => {',
  '        this.renderer.setSize(window.innerWidth, window.innerHeight);',
  '        this.camera.aspect = window.innerWidth / window.innerHeight;',
  '        this.camera.updateProjectionMatrix();',
  '      });',
  '      this.renderer.domElement.addEventListener("click",     (e) => this.handleRaycast(e, true));',
  '      this.renderer.domElement.addEventListener("mousemove", (e) => this.handleRaycast(e, false));',
  '      this.renderer.setAnimationLoop(() => this.animate());',
  '      setTimeout(() => {',
  '        const loader = document.getElementById("loader");',
  '        if (loader) loader.classList.add("hidden");',
  '        const cnt = document.getElementById("visible-count");',
  '        if (cnt) cnt.textContent = this.shopMgr.shops.length;',
  '      }, 1500);',
  '      if (window.ReactNativeWebView) {',
  '        window.ReactNativeWebView.postMessage(JSON.stringify({ type: "ready" }));',
  '      }',
  '    } catch(e) {',
  '      const msg = "EngineCore.init failed: " + e.message;',
  '      const sub = document.querySelector(".loader-subtitle");',
  '      if (sub) sub.innerHTML = "<span style=\\"color:red\\">" + msg + "</span>";',
  '      if (window.ReactNativeWebView) {',
  '        window.ReactNativeWebView.postMessage(JSON.stringify({ type: "error", error: msg }));',
  '      }',
  '    }',
  '  }',
  '  bindUI() {',
  '    const followBtn = document.getElementById("follow-btn");',
  '    if (followBtn) {',
  '      followBtn.onclick = () => {',
  '        const on = this.camCtrl.toggleFollowMode();',
  '        followBtn.classList.toggle("active", on);',
  '        if (on) this.camCtrl.setCamTarget(this.avatarSys.position.x, this.avatarSys.position.z);',
  '      };',
  '    }',
  '    const zi = document.getElementById("zoom-in");',
  '    const zo = document.getElementById("zoom-out");',
  '    if (zi) zi.onclick = () => { this.camCtrl.radius = Math.max(80,  this.camCtrl.radius - 40); };',
  '    if (zo) zo.onclick = () => { this.camCtrl.radius = Math.min(900, this.camCtrl.radius + 40); };',
  '    const closeBtn = document.getElementById("shop-panel-close");',
  '    if (closeBtn) closeBtn.onclick = () => {',
  '      document.getElementById("shop-panel").classList.remove("visible");',
  '      this.selectedShop = null;',
  '    };',
  '    const visitBtn = document.getElementById("shop-visit-btn");',
  '    if (visitBtn) visitBtn.onclick = () => {',
  '      if (this.selectedShop && window.ReactNativeWebView) {',
  '        window.ReactNativeWebView.postMessage(JSON.stringify({ type: "shop_selected", shop: this.selectedShop }));',
  '        document.getElementById("shop-panel").classList.remove("visible");',
  '      }',
  '    };',
  '  }',
  '  handleRaycast(e, isClick) {',
  '    if (!this.shopMgr.shops.length) return;',
  '    const mouse = new THREE.Vector2(',
  '      (e.clientX / window.innerWidth) * 2 - 1,',
  '      -(e.clientY / window.innerHeight) * 2 + 1',
  '    );',
  '    this.raycaster.setFromCamera(mouse, this.camera);',
  '    const hits = this.raycaster.intersectObjects(this.shopMgr.shops.map(s => s.mesh));',
  '    if (this.hoveredMesh) { this.hoveredMesh.material.emissive.setHex(0x000000); this.hoveredMesh = null; }',
  '    const tooltip = document.getElementById("hover-tooltip");',
  '    if (tooltip) tooltip.classList.remove("visible");',
  '    if (hits.length > 0) {',
  '      const hit = hits[0].object;',
  '      if (hit.userData && hit.userData.shop) {',
  '        this.hoveredMesh = hit;',
  '        hit.material.emissive.setHex(0x333333);',
  '        const shop = hit.userData.shop;',
  '        if (isClick) {',
  '          this.selectedShop = shop;',
  '          const t = document.getElementById("shop-title");    if (t) t.textContent = shop.name;',
  '          const c = document.getElementById("shop-category"); if (c) c.textContent = shop.type;',
  '          const r = document.getElementById("shop-rating");',
  '          if (r) r.innerHTML = "⭐ " + shop.rating + " <span style=\'color:#aaa;font-size:12px\'>(124 reviews)</span>";',
  '          document.getElementById("shop-panel").classList.add("visible");',
  '          if (window.ReactNativeWebView) {',
  '            window.ReactNativeWebView.postMessage(JSON.stringify({ type: "haptic" }));',
  '          }',
  '        } else if (tooltip) {',
  '          tooltip.textContent = (shop.icon || "") + " " + shop.name + " • " + shop.type + " • ⭐" + shop.rating;',
  '          tooltip.style.left = (e.clientX + 15) + "px";',
  '          tooltip.style.top  = (e.clientY - 15) + "px";',
  '          tooltip.classList.add("visible");',
  '        }',
  '      }',
  '    }',
  '  }',
  '  animate() {',
  '    const dt = Math.min(this.clock.getDelta(), 0.05);',
  '    const move   = this.inputMgr.getMovement();',
  '    const orbit  = this.inputMgr.getAndClearOrbitDelta();',
  '    const zoom   = this.inputMgr.getAndClearZoomDelta();',
  '    const newPos = this.physics.update(dt, move, this.avatarSys.position);',
  '    this.avatarSys.update(dt, newPos, this.physics.velocity);',
  '    this.camCtrl.update(dt, newPos, orbit, zoom);',
  '    this.envMgr.updateMinimap(newPos, this.shopMgr.shops);',
  '    this.renderer.render(this.scene, this.camera);',
  '  }',
  '}',
].join('\n');
