export const EnvironmentManagerStr = [
  'class EnvironmentManager {',
  '  constructor(scene, config, minimapCanvas) {',
  '    this.scene = scene;',
  '    this.C = config;',
  '    this.CITY_W = config.COLS * (config.BLOCK_W + config.ROAD_W) + config.ROAD_W;',
  '    this.CITY_D = config.ROWS * (config.BLOCK_D + config.ROAD_W) + config.ROAD_W;',
  '    this.CX = this.CITY_W / 2;',
  '    this.CZ = this.CITY_D / 2;',
  '    this.mmCanvas = minimapCanvas;',
  '    this.mmCtx = minimapCanvas ? minimapCanvas.getContext("2d") : null;',
  '  }',
  '  buildEnvironment() {',
  '    this.createLights();',
  '    this.createGround();',
  '    this.createRoads();',
  '  }',
  '  createLights() {',
  '    this.scene.add(new THREE.AmbientLight(0x404060, 0.6));',
  '    const sun = new THREE.DirectionalLight(0xfff5e0, 1.2);',
  '    sun.position.set(300, 500, 200);',
  '    sun.castShadow = true;',
  '    sun.shadow.mapSize.width = 1024;',
  '    sun.shadow.mapSize.height = 1024;',
  '    sun.shadow.camera.left = -500; sun.shadow.camera.right = 500;',
  '    sun.shadow.camera.top = 500; sun.shadow.camera.bottom = -500;',
  '    this.scene.add(sun);',
  '    this.scene.add(new THREE.PointLight(0x4466cc, 0.3, 0, 0).position.set(0, -50, 0) && new THREE.PointLight(0x4466cc, 0.3));',
  '  }',
  '  createGround() {',
  '    const mat = new THREE.MeshPhongMaterial({ color: 0x2a5a2a, shininess: 20 });',
  '    const g = new THREE.Mesh(new THREE.PlaneGeometry(this.CITY_W + 400, this.CITY_D + 400), mat);',
  '    g.rotation.x = -Math.PI / 2;',
  '    g.position.set(this.CX, -1, this.CZ);',
  '    g.receiveShadow = true; g.matrixAutoUpdate = false; g.updateMatrix();',
  '    this.scene.add(g);',
  '    const grassMat = new THREE.MeshPhongMaterial({ color: 0x3a7a3a });',
  '    const grassGeo = new THREE.BoxGeometry(0.5, 0.5, 0.5);',
  '    for (let i = 0; i < 150; i++) {',
  '      const gr = new THREE.Mesh(grassGeo, grassMat);',
  '      gr.scale.y = Math.random() * 0.7 + 0.2;',
  '      gr.position.set(Math.random() * this.CITY_W, -0.8, Math.random() * this.CITY_D);',
  '      gr.matrixAutoUpdate = false; gr.updateMatrix();',
  '      this.scene.add(gr);',
  '    }',
  '  }',
  '  createRoads() {',
  '    const roadMat = new THREE.MeshPhongMaterial({ color: 0x2a2a2a, shininess: 30 });',
  '    const lineMat = new THREE.MeshPhongMaterial({ color: 0xffdd88 });',
  '    const swMat   = new THREE.MeshPhongMaterial({ color: 0xaa9988, shininess: 40 });',
  '    const SX = this.C.BLOCK_W + this.C.ROAD_W;',
  '    const SZ = this.C.BLOCK_D + this.C.ROAD_W;',
  '    for (let r = 0; r <= this.C.ROWS; r++) {',
  '      this._strip(roadMat, lineMat, this.CX, r*SZ + this.C.ROAD_W/2, this.CITY_W, this.C.ROAD_W, false);',
  '    }',
  '    for (let c = 0; c <= this.C.COLS; c++) {',
  '      this._strip(roadMat, lineMat, c*SX + this.C.ROAD_W/2, this.CZ, this.C.ROAD_W, this.CITY_D, true);',
  '    }',
  '    const swGeo = new THREE.BoxGeometry(this.C.BLOCK_W, 0.4, this.C.BLOCK_D);',
  '    for (let c = 0; c < this.C.COLS; c++) {',
  '      for (let r = 0; r < this.C.ROWS; r++) {',
  '        const sw = new THREE.Mesh(swGeo, swMat);',
  '        sw.position.set(this.C.ROAD_W + c*SX + this.C.BLOCK_W/2, -0.3, this.C.ROAD_W + r*SZ + this.C.BLOCK_D/2);',
  '        sw.receiveShadow = true; sw.matrixAutoUpdate = false; sw.updateMatrix();',
  '        this.scene.add(sw);',
  '      }',
  '    }',
  '  }',
  '  _strip(roadMat, lineMat, cx, cz, w, d, vert) {',
  '    const road = new THREE.Mesh(new THREE.BoxGeometry(w, 0.3, d), roadMat);',
  '    road.position.set(cx, -0.2, cz);',
  '    road.receiveShadow = true; road.matrixAutoUpdate = false; road.updateMatrix();',
  '    this.scene.add(road);',
  '    const n = Math.floor((vert ? d : w) / 15);',
  '    const dGeo = new THREE.BoxGeometry(vert ? 0.3 : 4, 0.2, vert ? 4 : 0.3);',
  '    for (let i = 0; i < n; i++) {',
  '      const dash = new THREE.Mesh(dGeo, lineMat);',
  '      const off = -((vert ? d : w) / 2) + 8 + i * 15;',
  '      dash.position.set(vert ? cx : cx + off, -0.1, vert ? cz + off : cz);',
  '      dash.matrixAutoUpdate = false; dash.updateMatrix();',
  '      this.scene.add(dash);',
  '    }',
  '  }',
  '  updateMinimap(avatarPos, shops) {',
  '    if (!this.mmCtx) return;',
  '    const cv = this.mmCanvas;',
  '    this.mmCtx.fillStyle = "rgba(15,15,30,0.9)";',
  '    this.mmCtx.fillRect(0, 0, cv.width, cv.height);',
  '    this.mmCtx.strokeStyle = "rgba(108,99,255,0.3)";',
  '    this.mmCtx.lineWidth = 1;',
  '    for (let i = 0; i <= this.C.COLS; i++) {',
  '      const x = (i / this.C.COLS) * cv.width;',
  '      this.mmCtx.beginPath(); this.mmCtx.moveTo(x, 0); this.mmCtx.lineTo(x, cv.height); this.mmCtx.stroke();',
  '    }',
  '    for (let i = 0; i <= this.C.ROWS; i++) {',
  '      const y = (i / this.C.ROWS) * cv.height;',
  '      this.mmCtx.beginPath(); this.mmCtx.moveTo(0, y); this.mmCtx.lineTo(cv.width, y); this.mmCtx.stroke();',
  '    }',
  '    shops.forEach(item => {',
  '      const s = item.shop;',
  '      if (!s.coordinates) return;',
  '      const x = (s.coordinates.x / this.CITY_W) * cv.width;',
  '      const z = (s.coordinates.z / this.CITY_D) * cv.height;',
  '      this.mmCtx.fillStyle = "#" + s.color.toString(16).padStart(6, "0");',
  '      this.mmCtx.fillRect(x - 3, z - 3, 6, 6);',
  '    });',
  '    if (avatarPos) {',
  '      const x = (avatarPos.x / this.CITY_W) * cv.width;',
  '      const z = (avatarPos.z / this.CITY_D) * cv.height;',
  '      this.mmCtx.fillStyle = "#6c63ff";',
  '      this.mmCtx.beginPath(); this.mmCtx.arc(x, z, 5, 0, Math.PI * 2); this.mmCtx.fill();',
  '      this.mmCtx.fillStyle = "white";',
  '      this.mmCtx.beginPath(); this.mmCtx.arc(x, z, 2, 0, Math.PI * 2); this.mmCtx.fill();',
  '    }',
  '  }',
  '}',
].join('\n');
