// InputManager - bundled as a plain string to avoid Metro template literal parsing issues
export const InputManagerStr = [
  'class InputManager {',
  '  constructor(canvas) {',
  '    this.canvas = canvas;',
  '    this.moveVector = new THREE.Vector2(0, 0);',
  '    this.orbitDelta = new THREE.Vector2(0, 0);',
  '    this.zoomDelta = 0;',
  '    this.isDragging = false;',
  '    this.keys = { w: false, a: false, s: false, d: false };',
  '    this.joystickActive = false;',
  '    this.joystickStart = { x: 0, y: 0 };',
  '    this.previousTouch = null;',
  '    this.initialPinchDist = null;',
  '    this.initKeyboard();',
  '    this.initJoystick();',
  '    this.initTouchCamera();',
  '  }',
  '  initKeyboard() {',
  '    window.addEventListener("keydown", (e) => {',
  '      const k = e.key.toLowerCase();',
  '      if (k in this.keys) this.keys[k] = true;',
  '      this.updateMoveVector();',
  '    });',
  '    window.addEventListener("keyup", (e) => {',
  '      const k = e.key.toLowerCase();',
  '      if (k in this.keys) this.keys[k] = false;',
  '      this.updateMoveVector();',
  '    });',
  '  }',
  '  updateMoveVector() {',
  '    if (this.joystickActive) return;',
  '    let x = 0; let y = 0;',
  '    if (this.keys.w) y -= 1;',
  '    if (this.keys.s) y += 1;',
  '    if (this.keys.a) x -= 1;',
  '    if (this.keys.d) x += 1;',
  '    if (x !== 0 || y !== 0) { const l = Math.sqrt(x*x+y*y); x/=l; y/=l; }',
  '    this.moveVector.set(x, y);',
  '  }',
  '  initJoystick() {',
  '    const base = document.getElementById("joystick-base");',
  '    const knob = document.getElementById("joystick-knob");',
  '    if (!base || !knob) return;',
  '    const maxDist = 40;',
  '    const handleStart = (e) => {',
  '      e.preventDefault();',
  '      this.joystickActive = true;',
  '      const rect = base.getBoundingClientRect();',
  '      this.joystickStart = { x: rect.left + rect.width/2, y: rect.top + rect.height/2 };',
  '    };',
  '    const handleMove = (e) => {',
  '      if (!this.joystickActive) return;',
  '      e.preventDefault();',
  '      const touch = e.touches ? e.touches[0] : e;',
  '      let dx = touch.clientX - this.joystickStart.x;',
  '      let dy = touch.clientY - this.joystickStart.y;',
  '      const dist = Math.sqrt(dx*dx + dy*dy);',
  '      const vdx = dist > maxDist ? (dx/dist)*maxDist : dx;',
  '      const vdy = dist > maxDist ? (dy/dist)*maxDist : dy;',
  '      knob.style.transform = "translate(calc(-50% + " + vdx + "px), calc(-50% + " + vdy + "px))";',
  '      let vecX = dx / maxDist; let vecY = dy / maxDist;',
  '      const len = Math.sqrt(vecX*vecX + vecY*vecY);',
  '      if (len > 1.0) { vecX /= len; vecY /= len; }',
  '      this.moveVector.set(vecX, vecY);',
  '    };',
  '    const handleEnd = () => {',
  '      this.joystickActive = false;',
  '      knob.style.transform = "translate(-50%, -50%)";',
  '      this.moveVector.set(0, 0);',
  '      this.updateMoveVector();',
  '    };',
  '    base.addEventListener("touchstart", handleStart, { passive: false });',
  '    base.addEventListener("touchmove", handleMove, { passive: false });',
  '    base.addEventListener("touchend", handleEnd);',
  '    base.addEventListener("mousedown", handleStart);',
  '    window.addEventListener("mousemove", handleMove);',
  '    window.addEventListener("mouseup", handleEnd);',
  '  }',
  '  initTouchCamera() {',
  '    if (!this.canvas) return;',
  '    this.canvas.addEventListener("wheel", (e) => {',
  '      this.zoomDelta += e.deltaY * 0.5;',
  '      e.preventDefault();',
  '    }, { passive: false });',
  '    const handleTouchStart = (e) => {',
  '      if (e.target.closest("#joystick-container")) return;',
  '      if (e.touches.length === 1) {',
  '        this.isDragging = true;',
  '        this.previousTouch = { x: e.touches[0].clientX, y: e.touches[0].clientY };',
  '      } else if (e.touches.length === 2) {',
  '        this.isDragging = false;',
  '        const dx = e.touches[0].clientX - e.touches[1].clientX;',
  '        const dy = e.touches[0].clientY - e.touches[1].clientY;',
  '        this.initialPinchDist = Math.sqrt(dx*dx + dy*dy);',
  '      }',
  '    };',
  '    const handleTouchMove = (e) => {',
  '      if (e.touches.length === 2 && this.initialPinchDist) {',
  '        const dx = e.touches[0].clientX - e.touches[1].clientX;',
  '        const dy = e.touches[0].clientY - e.touches[1].clientY;',
  '        const dist = Math.sqrt(dx*dx + dy*dy);',
  '        const factor = this.initialPinchDist / dist;',
  '        if (factor > 1.05) this.zoomDelta += 10;',
  '        else if (factor < 0.95) this.zoomDelta -= 10;',
  '        this.initialPinchDist = dist;',
  '        e.preventDefault(); return;',
  '      }',
  '      if (!this.isDragging || !this.previousTouch || e.touches.length !== 1) return;',
  '      const cur = { x: e.touches[0].clientX, y: e.touches[0].clientY };',
  '      this.orbitDelta.x += (cur.x - this.previousTouch.x) * 0.01;',
  '      this.orbitDelta.y += (cur.y - this.previousTouch.y) * 0.01;',
  '      this.previousTouch = cur;',
  '      e.preventDefault();',
  '    };',
  '    const handleTouchEnd = (e) => {',
  '      if (e.touches.length < 2) this.initialPinchDist = null;',
  '      if (e.touches.length === 0) { this.isDragging = false; this.previousTouch = null; }',
  '    };',
  '    this.canvas.addEventListener("touchstart", handleTouchStart, { passive: false });',
  '    this.canvas.addEventListener("touchmove", handleTouchMove, { passive: false });',
  '    this.canvas.addEventListener("touchend", handleTouchEnd);',
  '  }',
  '  getMovement() { return this.moveVector; }',
  '  getAndClearOrbitDelta() {',
  '    const x = this.orbitDelta.x; const y = this.orbitDelta.y;',
  '    this.orbitDelta.set(0, 0); return { x, y };',
  '  }',
  '  getAndClearZoomDelta() {',
  '    const z = this.zoomDelta; this.zoomDelta = 0; return z;',
  '  }',
  '}',
].join('\n');
