export const PhysicsControllerStr = [
  'class PhysicsController {',
  '  constructor(config) {',
  '    this.CONFIG = config;',
  '    this.CITY_W = config.COLS * (config.BLOCK_W + config.ROAD_W) + config.ROAD_W;',
  '    this.CITY_D = config.ROWS * (config.BLOCK_D + config.ROAD_W) + config.ROAD_W;',
  '    this.velocity = new THREE.Vector3();',
  '    this.MAX_SPEED = 30.0;',
  '    this.ACCELERATION = 80.0;',
  '    this.FRICTION_COEFF = 10.0;',
  '    this.colliders = [];',
  '    this.nextPos = new THREE.Vector3();',
  '    this.avatarBox = new THREE.Box3();',
  '    this.avatarSize = new THREE.Vector3(3.0, 9.0, 3.0);',
  '  }',
  '  addCollider(box3) { this.colliders.push(box3); }',
  '  update(deltaTime, moveVector, currentPosition) {',
  '    const friction = Math.exp(-this.FRICTION_COEFF * deltaTime);',
  '    if (moveVector.lengthSq() > 0) {',
  '      this.velocity.x += moveVector.x * this.ACCELERATION * deltaTime;',
  '      this.velocity.z += moveVector.y * this.ACCELERATION * deltaTime;',
  '      const speed = Math.sqrt(this.velocity.x**2 + this.velocity.z**2);',
  '      if (speed > this.MAX_SPEED) {',
  '        this.velocity.x = (this.velocity.x / speed) * this.MAX_SPEED;',
  '        this.velocity.z = (this.velocity.z / speed) * this.MAX_SPEED;',
  '      }',
  '    } else {',
  '      this.velocity.x *= friction;',
  '      this.velocity.z *= friction;',
  '    }',
  '    if (Math.abs(this.velocity.x) < 0.1) this.velocity.x = 0;',
  '    if (Math.abs(this.velocity.z) < 0.1) this.velocity.z = 0;',
  '    this.nextPos.copy(currentPosition);',
  '    this.nextPos.x += this.velocity.x * deltaTime;',
  '    this.nextPos.z += this.velocity.z * deltaTime;',
  '    this.avatarBox.setFromCenterAndSize(',
  '      new THREE.Vector3(this.nextPos.x, this.avatarSize.y / 2, this.nextPos.z),',
  '      this.avatarSize',
  '    );',
  '    let collided = false;',
  '    for (let box of this.colliders) {',
  '      if (this.avatarBox.intersectsBox(box)) { collided = true; break; }',
  '    }',
  '    const PAD = 15;',
  '    if (this.nextPos.x < PAD || this.nextPos.x > this.CITY_W - PAD ||',
  '        this.nextPos.z < PAD || this.nextPos.z > this.CITY_D - PAD) { collided = true; }',
  '    if (collided) {',
  '      this.velocity.x *= 0.1;',
  '      this.velocity.z *= 0.1;',
  '      return currentPosition;',
  '    }',
  '    return this.nextPos;',
  '  }',
  '}',
].join('\n');
