export const ShopManagerStr = [
  'class ShopManager {',
  '  constructor(scene) {',
  '    this.scene = scene;',
  '    this.shops = [];',
  '    this.matCache = {};',
  '  }',
  '  generateEnvironment(config, shopList, physics) {',
  '    // Fallback: if no shops provided, create default shops',
  '    const shops = shopList && shopList.length > 0 ? shopList : this.getDefaultShops();',
  '    const STEP_X = config.BLOCK_W + config.ROAD_W;',
  '    const STEP_Z = config.BLOCK_D + config.ROAD_W;',
  '    shops.forEach((shop, i) => {',
  '      const col = i % config.COLS;',
  '      const row = Math.floor(i / config.COLS);',
  '      const bx = config.ROAD_W + col * STEP_X + config.BLOCK_W / 2;',
  '      const bz = config.ROAD_W + row * STEP_Z + config.BLOCK_D / 2;',
  '      this.buildShop(shop, bx, bz, col, row, config, physics);',
  '    });',
  '  }',
  '  getDefaultShops() {',
  '    return [',
  '      { id: 0, name: "TechZone", type: "Electronics", category: "Electronics", color: 0x1565C0, accent: 0x42A5F5, height: 45, icon: "⚡", rating: 4.5, price: "$$", description: "Latest gadgets & electronics", address: "123 Tech St" },',
  '      { id: 1, name: "Style & Co", type: "Fashion", category: "Fashion", color: 0xAD1457, accent: 0xF48FB1, height: 40, icon: "👗", rating: 4.2, price: "$$$", description: "Premium fashion", address: "456 Fashion Ave" },',
  '      { id: 2, name: "Bean & Brew", type: "Cafe", category: "Food", color: 0x4E342E, accent: 0xA1887F, height: 35, icon: "☕", rating: 4.8, price: "$", description: "Artisan coffee", address: "789 Coffee Ln" },',
  '      { id: 3, name: "FreshMart", type: "Grocery", category: "Food", color: 0x2E7D32, accent: 0x81C784, height: 38, icon: "🥬", rating: 4.3, price: "$", description: "Farm fresh produce", address: "321 Market Rd" },',
  '      { id: 4, name: "PageTurner", type: "Bookstore", category: "Entertainment", color: 0xBF360C, accent: 0xFF8A50, height: 42, icon: "📚", rating: 4.6, price: "$", description: "Thousands of books", address: "555 Book St" },',
  '      { id: 5, name: "HealthPlus", type: "Pharmacy", category: "Lifestyle", color: 0x00695C, accent: 0x80CBC4, height: 32, icon: "💊", rating: 4.1, price: "$$", description: "Pharmaceutical products", address: "666 Health Ave" },',
  '      { id: 6, name: "La Piazza", type: "Restaurant", category: "Food", color: 0xB71C1C, accent: 0xEF9A9A, height: 44, icon: "🍕", rating: 4.7, price: "$$", description: "Authentic Italian cuisine", address: "777 Pizza Ln" },',
  '      { id: 7, name: "Luxe Gems", type: "Jewelry", category: "Lifestyle", color: 0xF57F17, accent: 0xFFD54F, height: 36, icon: "💎", rating: 4.9, price: "$$$$", description: "Fine jewelry", address: "888 Jewel St" },',
  '      { id: 8, name: "TestShop1", type: "Test", category: "Lifestyle", color: 0xFF5722, accent: 0xFFAB91, height: 40, icon: "🛒", rating: 4.0, price: "$", description: "Test shop 1", address: "111 Test St" },',
  '      { id: 9, name: "TestShop2", type: "Test", category: "Lifestyle", color: 0x00BCD4, accent: 0x80DEEA, height: 45, icon: "🛒", rating: 4.1, price: "$$", description: "Test shop 2", address: "222 Test Ave" },',
  '      { id: 10, name: "TestShop3", type: "Test", category: "Entertainment", color: 0x9C27B0, accent: 0xCE93D8, height: 35, icon: "🛒", rating: 4.2, price: "$", description: "Test shop 3", address: "333 Test Ln" },',
  '      { id: 11, name: "TestShop4", type: "Test", category: "Fashion", color: 0xE91E63, accent: 0xF48FB1, height: 38, icon: "🛒", rating: 4.3, price: "$$", description: "Test shop 4", address: "444 Test Rd" },',
  '    ];',
  '  }',
  '  getMat(color, shininess) {',
  '    const key = color + "_" + shininess;',
  '    if (!this.matCache[key]) {',
  '      this.matCache[key] = new THREE.MeshPhongMaterial({ color, shininess });',
  '    }',
  '    return this.matCache[key];',
  '  }',
  '  buildShop(shop, x, z, col, row, config, physics) {',
  '    const group = new THREE.Object3D();',
  '    group.position.set(x, 0, z);',
  '    group.matrixAutoUpdate = false;',
  '    this.scene.add(group);',
  '    const w = config.BLOCK_W * 0.7;',
  '    const d = config.BLOCK_D * 0.7;',
  '    const h = shop.height || 20;',
  '    shop.coordinates = { x, z, col, row };',
  '    const body = new THREE.Mesh(',
  '      new THREE.BoxGeometry(w, h, d),',
  '      this.getMat(shop.color, 50)',
  '    );',
  '    body.position.y = h / 2;',
  '    body.castShadow = true; body.receiveShadow = true;',
  '    body.userData = { shop };',
  '    body.matrixAutoUpdate = false; body.updateMatrix();',
  '    group.add(body);',
  '    this.shops.push({ mesh: body, shop });',
  '    if (physics) {',
  '      const box = new THREE.Box3().setFromCenterAndSize(',
  '        new THREE.Vector3(x, h / 2, z),',
  '        new THREE.Vector3(w, h, d)',
  '      );',
  '      physics.addCollider(box);',
  '    }',
  '    const roof = new THREE.Mesh(',
  '      new THREE.BoxGeometry(w + 2, 1.5, d + 2),',
  '      this.getMat(shop.accent, 70)',
  '    );',
  '    roof.position.y = h + 0.75;',
  '    roof.matrixAutoUpdate = false; roof.updateMatrix();',
  '    group.add(roof);',
  '    const winMat = new THREE.MeshPhongMaterial({ color: 0x88aaff, emissive: 0x224466 });',
  '    const winGeo = new THREE.BoxGeometry(4, 5, 0.2);',
  '    for (let i = 0; i < 3; i++) {',
  '      const win = new THREE.Mesh(winGeo, winMat);',
  '      win.position.set(-w/3 + i * w/3, h/2, d/2 + 0.1);',
  '      win.matrixAutoUpdate = false; win.updateMatrix();',
  '      group.add(win);',
  '    }',
  '    const canvas = document.createElement("canvas");',
  '    canvas.width = 512; canvas.height = 128;',
  '    const ctx = canvas.getContext("2d");',
  '    const grad = ctx.createLinearGradient(0, 0, 512, 0);',
  '    grad.addColorStop(0, "#" + shop.color.toString(16).padStart(6, "0"));',
  '    grad.addColorStop(1, "#" + shop.accent.toString(16).padStart(6, "0"));',
  '    ctx.fillStyle = grad; ctx.fillRect(0, 0, 512, 128);',
  '    ctx.strokeStyle = "white"; ctx.lineWidth = 3; ctx.strokeRect(5, 5, 502, 118);',
  '    ctx.fillStyle = "white"; ctx.font = "bold 48px Arial";',
  '    ctx.textAlign = "center"; ctx.textBaseline = "middle";',
  '    ctx.fillText(shop.name, 256, 64);',
  '    const tex = new THREE.Texture(canvas); tex.needsUpdate = true;',
  '    const sign = new THREE.Mesh(',
  '      new THREE.PlaneGeometry(w * 0.7, 6),',
  '      new THREE.MeshBasicMaterial({ map: tex, transparent: true })',
  '    );',
  '    sign.position.set(0, h - 8, d / 2 + 0.1);',
  '    sign.matrixAutoUpdate = false; sign.updateMatrix();',
  '    group.add(sign);',
  '    group.updateMatrix();',
  '  }',
  '}',
].join('\n');
